---
title: "proj2"
author: "Jiayi Shi"
date: "2025-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
warning = FALSE,
message=F,
fig.width = 6,
fig.asp = .6,
out.width = "90%")
library(tidyverse)
library(table1)
library(tableone)
library(gtsummary)
library(knitr)
library(patchwork)
library(table1)
```

```{r}
library(survival)
library(survminer)

data <- read.table("menopause.dat", header=FALSE, col.names=c("id", "intake_age", "menopause_age", "menopause", "race", "education"))

data <- data %>% mutate(
  menopause = factor(menopause, labels = c("Censored", "Menopause")),
  race = factor(race, labels = c("White non-Hispanic", "Black non-Hispanic", "Other Ethnicity")),
  education = factor(education, labels = c("Post-graduate", "College Graduate", "Some College", "High School or less")),
  menopause_time = menopause_age - intake_age
)

label(data$intake_age) <- "Intake Age (years)"
label(data$menopause_age) <- "Menopause Age (years)"
label(data$menopause) <- "Menopause Status"
label(data$race) <- "Ethnicity"
label(data$education) <- "Education Level"

table1(~ intake_age+menopause_age+race+education | menopause, data, overall = F)

df <- data %>% 
  mutate(menopause = as.numeric(menopause))
```

```{r A1a}
### (Ia) Estimate the median menopause time assuming an exponential distribution
mod1 <- survreg(Surv(menopause_time, menopause) ~ 1, data=df, dist="exponential")
lamda <- exp(-summary(mod1)$coef)
est <- log(2) / lamda ##12.2
predict(mod1, type = "quantile", p = 0.5, se.fit = TRUE)
ciTools::add_quantile(df, mod1, p = 0.5, names = c("Median", "Lower", "Upper"))
## (10.09,14.75)
# Estimate lambda (rate parameter)
N <- nrow(data)
r <- sum(data$menopause=="Menopause")
lambda_hat <- 1 / (sum(data$menopause_time)/r)
# Estimate the median menopause time
median_est <- log(2) / lambda_hat
# Compute standard error using the Delta Method
se_median <- log(2) / (lambda_hat * sqrt(r))
# Compute the 95% confidence interval
ci_lower <- median_est - 1.96 * se_median
ci_upper <- median_est + 1.96 * se_median
cat("Estimated median menopause time (Exponential):", median_estimate, "\n")
cat("95% CI:", c(ci_lower, ci_upper), "\n")


```

```{r A1b}
### (Ib) Compute Kaplan-Meier survival estimate

km_fit <- survfit(Surv(menopause_time, menopause) ~ 1, data = df)
summary(km_fit)

# Extract survival data from the Kaplan-Meier fit
km_data <- data.frame(time = km_fit$time,
                      survival = km_fit$surv,
                      lower = km_fit$lower,
                      upper = km_fit$upper)

# KM survival curve
ggplot(km_data, aes(x = time, y = survival)) +
  geom_step(size = 1, color = "#2C3E50") + 
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#BDC3C7", alpha = 0.3) +
  scale_y_continuous(limits = c(0:1))+
  labs(x = "Time to Menopause (years)",
       y = "Survival Probability") +
  scale_x_continuous(breaks = seq(0, 6, by=1))+
  theme_classic() +  
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))

cat("Estimated median time to menopause (Kaplan-Meier):", summary(km_fit)$table["median"], "\n")
```

```{r A2}
# Fit the Cox proportional hazards model
cox_model <- coxph(Surv(menopause_time, menopause) ~ race + education + intake_age, data = df)

cox_model2 <- coxph(Surv(menopause_time, menopause) ~ intake_age, data = df)

cox_model3 <- coxph(Surv(menopause_time, menopause) ~ education + intake_age, data = df)

# Display model summary
summary(cox_model)

anova(cox_model2,cox_model)

# Plot Schoenfeld residuals to visualize proportional hazards assumption
cox.zph_test <- cox.zph(cox_model)
ggcoxzph(cox.zph_test)

```


```{r B3}
### (III) Compute Kaplan-Meier for menopause_age
km_fit_age <- survfit(Surv(intake_age, menopause_age, menopause) ~ 1, data = df)

summary(km_fit_age)

# Extract survival data from the Kaplan-Meier fit
km_data <- data.frame(time = km_fit_age$time,
                      survival = km_fit_age$surv,
                      lower = km_fit_age$lower,
                      upper = km_fit_age$upper)

# Plot using ggplot
ggplot(km_data, aes(x = time, y = survival)) +
  geom_step(size = 1, color = "#2C3E50") +  # Survival curve
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#BDC3C7", alpha = 0.3) +  # Confidence interval shading
  scale_x_continuous(breaks = seq(44, 60, by = 1), limits = c(44, 60)) +  
  labs(x = "Menopause Age (years)",
       y = "Survival Probability") +
  theme_classic() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))

cat("Estimated median menopause age (Kaplan-Meier):", summary(km_fit_age)$table["median"], "years.\n")

# Assume exponential distribution
lambda_hat <- 1 / (sum(data$menopause_age)/sum(data$menopause=="Menopause"))

median_exp <- log(2) / lambda_hat
cat("Estimated Median (Exponential Model):", median_exp, "years.\n")

```

```{r B4}
### (IV) Test for Survival Differences by Race
# KM curves handling Left Truncation
km_fit_race <- survfit(Surv(intake_age, menopause_age, menopause) ~ race, data = df)

summary(km_fit_race)
km_plot <- ggsurvplot(km_fit_race, data = df, conf.int = TRUE, 
           ggtheme = theme_classic(), xlab="Menopause Age (years)", 
           ylab="Survival Probability", xlim=c(44,60),
           legend.title="Race", legend.labs=c("White", "Black", "Other"))
km_plot$plot +
  scale_x_continuous(breaks = seq(44, 60, by = 1)) 

# Generalized Log-rank test
## Gehan-Breslow-Wilcoxon Test (Early Failures Weighted Higher)

# Log-rank test
survdiff(Surv(menopause_age, menopause) ~ race, data = df)
#race not significant
```

```{r B5}
### (V) Cox Regression for Menopause Age with Race, adjusting for education, Handling Left Truncation
cox_model_age <- coxph(Surv(intake_age, menopause_age, menopause) ~ race + education, data = df)
summary(cox_model_age)

cox_model_age_reduced <- coxph(Surv(intake_age, menopause_age, menopause) ~ education, data = df)

anova(cox_model_age, cox_model_age_reduced, test = "LRT")

# (Vb) Relative risk estimates for Black vs Other controlling for education

dd <- df
dd$race <- relevel(factor(df$race), ref = "Other Ethnicity")

# Fit the Cox model with new reference group
cox_model_ref_other <- coxph(Surv(intake_age, menopause_age, menopause) ~ race + education, data = dd)

summary(cox_model_ref_other)

# Extract coefficients and standard errors
#coef_black <- coef(cox_model_age)["raceBlack non-Hispanic"]
#coef_other <- coef(cox_model_age)["raceOther Ethnicity"]
#SE_black <- summary(cox_model_age)$coef["raceBlack non-Hispanic", #"se(coef)"]
#SE_other <- summary(cox_model_age)$coef["raceOther Ethnicity", #"se(coef)"]
#
## Compute log HR ratio and standard error
#log_HR_ratio <- coef_black - coef_other
#SE_log_HR_ratio <- sqrt(SE_black^2 + SE_other^2)
#
## Compute 95% CI
#lower_CI <- exp(log_HR_ratio - 1.96 * SE_log_HR_ratio)
#upper_CI <- exp(log_HR_ratio + 1.96 * SE_log_HR_ratio)
#
## Print results
#cat("HR Ratio (Black vs. Other Ethnicity):", exp(log_HR_ratio), "\n")
#cat("95% Confidence Interval: (", lower_CI, ",", upper_CI, ")\n")
#
#vcov_matrix <- vcov(cox_model_age)
#vcov_matrix["raceBlack non-Hispanic", "raceOther Ethnicity"]


# (Vc) Baseline survival function for White non-Hispanic with Post-graduate education
base_surv <- survfit(cox_model_age, newdata = data.frame(race = "White non-Hispanic", education = "Post-graduate"))
summary(base_surv)

cat("Estimated median menopause age (Kaplan-Meier):", summary(base_surv)$table["median"], "years.\n")

p <- ggsurvplot(base_surv, conf.inf = T, data=df,xlim=c(44,60),ggtheme = theme_classic(), xlab="Menopause Age (years)", ylab="Baseline Survival Probability", legend = "none")
p$plot +
  scale_x_continuous(breaks = seq(44, 60, by = 1)) 

# (Vd) Check proportional hazards assumption
cox.zph(cox_model_age)

```

